Repository InsideOutXminDay/minday, pull requests merged in 2024-07, with the labels that each got.

#18 NewPage/layout
  src/App.js
  src/pages/new.js
  src/pages/post.js
  src/styles/new.css
  src/styles/post.css
Labels: FE

#20 mind page / layout-button
  src/App.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
  src/styles/new.css
  src/styles/post.css
Labels: FE

#25 feat/edit page-layout
  src/App.js
  src/pages/edit.js
  src/pages/post.js
  src/styles/edit.css
  src/styles/new.css
Labels: FE

#30 feat/detail page - layout, css, comment
  package-lock.json
  src/App.js
  src/pages/detail.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
  src/styles/detail.css
  src/styles/edit.css
  src/styles/new.css
  src/styles/post.css
Labels: FE

#37 feat/detail page - data connect
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
  src/styles/detail.css
  src/styles/edit.css
  src/styles/new.css
  src/styles/post.css
Labels: FE

#45 07/09 account-modify
  package.json
  settingserver/app.js
  settingserver/package.json
  settingserver/userdata.json
  src/components/SettingAccount.js
Labels: BE, DB

#49 feat/detail page/ new post, new comment
  db/dbserver.js
  package-lock.json
  package.json
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: BE, DB, Update

#51 07/10 fix settingPage
  settingserver/app.js
  settingserver/userdata.json
  src/components/SettingAccount.js
  src/pages/Contents.js
  src/pages/SettingPage.js
  src/styles/SettingPage.css
Labels: Trouble Shoot

#59 feat/delete comment, new page re-rendering
  db/dbserver.js
  src/pages/detail.js
  src/pages/edit.js
  src/pages/new.js
Labels: BE, FE

#62 combine/back-end first commit
  combine/back.combine.db.js
  combine/back.combine.js
  package.json
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: BE

#76 fix/detail page css
  combine/server.js
  src/pages/detail.js
  src/pages/mind.js
  src/pages/post.js
  src/styles/detail.css
  src/styles/edit.css
  src/styles/post.css
Labels: Trouble Shoot

#77 07/12 fix settingpage error
  combine/server.js
  package-lock.json
  package.json
  settingserver/userdata.json
  src/components/SettingAccount.js
Labels: Trouble Shoot

#81 chore/edit server.js parenthesis
  combine/server.js
Labels: Simple

#90 fix/organize-files #88
  combine/db.js
  src/components/Intros/IntroCheckList.js
  src/components/Intros/IntroCommunity.js
  src/components/Intros/IntroContents.js
  src/components/Intros/IntroDiary.js
  src/components/Intros/IntroFooter.js
  src/components/Intros/IntroHeader.js
  src/components/Intros/IntroMain.js
  src/components/Intros/IntroServices.js
  src/components/Login/LoginForm.js
  src/components/SignUp/SignUpForm.js
  src/pages/Intro.js
  src/pages/Login.js
  src/pages/SignUp.js
  src/styles/Intros/Intro.css
  src/styles/Intros/IntroCheckList.css
  src/styles/Intros/IntroCommunity.css
  src/styles/Intros/IntroContents.css
  src/styles/Intros/IntroDiary.css
  src/styles/Intros/IntroFooter.css
  src/styles/Intros/IntroHeader.css
  src/styles/Intros/IntroMain.css
  src/styles/Intros/IntroServices.css
  src/styles/Login/LoginForm.css
  src/styles/SignUp/SignUpForm.css
Labels: Simple

#91 community feat's style files separation of concerns
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
  src/styles/community/detail.css
  src/styles/community/edit.css
  src/styles/community/new.css
  src/styles/community/post.css
Labels: Simple

#99 07/16 contents page 수정
  src/components/Contents/Category.js
  src/components/Contents/ContentsView.js
  src/components/Contents/SubCategory.js
  src/components/Setting/SettingAccount.js
  src/pages/Contents.js
  src/pages/SettingPage.js
  src/styles/Contents/Category.css
  src/styles/Contents/Contents.css
  src/styles/Contents/ContentsView.css
  src/styles/Contents/SubCategory.css
  src/styles/Setting/SettingPage.css
Labels: FE, Update

#101 Update/signup
  combine/server.js
  package-lock.json
  package.json
  src/components/Auth/LoginForm.js
  src/components/Auth/Modal.js
  src/components/Auth/SignUpForm.js
  src/components/SignUp/SignUpForm.js
  src/pages/Login.js
  src/pages/SignUp.js
  src/styles/Auth/LoginForm.css
  src/styles/Auth/Modal.css
  src/styles/Auth/SignUpForm.css
Labels: Update

#116 DB/table create, insert Mockup Data
  .gitignore
  combine/db.js
  combine/server.js
  package-lock.json
  package.json
  server/app.js
  src/components/Auth/LoginForm.js
  src/components/Auth/SignUpForm.js
  src/components/HomexDiary/CheckList/CheckItem.js
  src/components/HomexDiary/Paragraph.js
  src/pages/Ask.js
  src/pages/Home.js
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: BE, DB, Simple

#120 feat/react-player
  src/components/Contents/ContentsView.js
  src/styles/Contents/ContentsView.css
Labels: FE, Update

#126 feat/login-auth
  src/App.js
  src/components/Auth/LoginForm.js
  src/components/Auth/SignUpForm.js
  src/styles/Auth/LoginForm.css
Labels: BE, DB, Update

#127 chore/ sever code delete
  combine/db.js
  combine/server.js
  db/dbserver.js
  package-lock.json
  package.json
  server/.gitignore
  server/app.js
  server/package-lock.json
  server/package.json
  settingserver/app.js
  settingserver/package.json
  settingserver/userdata.json
Labels: Simple

#131 fix: err from using authenticateToken #130
  src/App.js
  src/components/Ask/StateCheck.js
  src/components/HomexDiary/CheckList/CheckItem.js
  src/pages/Ask.js
  src/pages/Diary.js
  src/pages/NewDiary.js
  src/util.js
Labels: BE, FE, Trouble Shoot

#135 Community feat/ Code reform due to sequelize
  src/App.js
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
  src/styles/community/post.css
Labels: FE

#150 Chore:clean up code
  src/App.js
  src/components/Ask/StateCheck.js
  src/components/Auth/LoginForm.js
  src/components/Auth/SignUpForm.js
  src/components/Contents/SubCategory.js
  src/components/Header.js
  src/components/HomexDiary/CheckList/CheckItem.js
  src/components/HomexDiary/DiaryEditor.js
  src/components/Setting/SettingAccount.js
  src/pages/Ask.js
  src/pages/Contents.js
  src/pages/NewDiary.js
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: FE, Update, Simple

#152 change 'alert' to 'snackbar' community feat
  package-lock.json
  package.json
  src/pages/detail.js
  src/pages/edit.js
  src/pages/new.js
Labels: FE, Update

#157 update/id_user props로 전달
  src/App.js
  src/components/Auth/LoginForm.js
  src/components/Intros/IntroHeader.js
  src/pages/Intro.js
Labels: FE, Update

#154 community feat: Delete overlap items
  src/components/Header.js
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: Simple

#159 Style/enhance page styling
  src/components/Header.js
  src/components/HomexDiary/CheckList/CheckItem.js
  src/pages/Contents.js
  src/styles/Ask/StateCheck.css
  src/styles/Contents/Category.css
  src/styles/Contents/Contents.css
  src/styles/Contents/ContentsView.css
  src/styles/Contents/SubCategory.css
  src/styles/Header.css
  src/styles/HomexDiary/Calendar.css
  src/styles/HomexDiary/CheckList/CheckItem.css
  src/styles/HomexDiary/CheckList/CheckList.css
  src/styles/HomexDiary/Paragraph.css
  src/styles/Setting/SettingPage.css
Labels: FE

#160 fix/ Apply user ID
  src/components/Setting/SettingAccount.js
  src/pages/Contents.js
  src/pages/Diary.js
  src/pages/Home.js
  src/pages/NewDiary.js
  src/pages/SettingPage.js
Labels: Trouble Shoot

#162 fix: UserID-Related Errors #161
  src/components/Header.js
  src/pages/Home.js
  src/pages/detail.js
  src/pages/edit.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: Trouble Shoot

#164 fix/community user id error #163
  src/pages/detail.js
  src/pages/mind.js
  src/pages/new.js
  src/pages/post.js
Labels: Trouble Shoot

#167 fix: user nickname box error & anonymity icon
  src/pages/detail.js
  src/styles/community/detail.css
Labels: FE

#168 Community feat design update
  src/pages/detail.js
  src/pages/edit.js
  src/pages/new.js
  src/styles/community/detail.css
  src/styles/community/edit.css
  src/styles/community/new.css
  src/styles/community/post.css
Labels: FE

#171 Fix/empty input submit error
  src/components/Auth/LoginForm.js
  src/components/Auth/SignUpForm.js
Labels: FE, Trouble Shoot

#172 fix Community error
  src/pages/detail.js
  src/pages/new.js
  src/styles/community/detail.css
  src/styles/community/post.css
Labels: FE, Trouble Shoot

#178 fix/Community comment api & detail page css
  src/pages/detail.js
  src/styles/community/detail.css
Labels: Trouble Shoot

#183 fix/detail page anonymity icon #182
  src/styles/community/detail.css
  src/styles/community/post.css
Labels: Trouble Shoot
